---
    - name: create instance profile
      become: no
      local_action: >
        shell {{ role_path }}/files/create_empty_instance_profile.sh
        {{ lookup('env', 'AWS_PROFILE') | default('default', true) }}
        {{ aws_role_name }} {{ instance_profile_name }}
      register: profile_result

    - debug:
        var: profile_result





